ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8083
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password